apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcustomrepos.github.kasnockndave.dev
spec:
  group: github.kasnockndave.dev
  names:
    kind: xCustomRepo
    plural: xcustomrepos
  claimNames:
    kind: CustomRepo
    plural: customrepos
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    repoName:
                      type: string
                  required:
                    - repoName
              required:
                - parameters
