apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-example
spec:
  revisionHistoryLimit: 0
  project: default
  source:
    repoURL: https://github.com/XXXLutz/crossplane-local-example.git
    targetRevision: main
    path: claims
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: false
