apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  namespace: crossplane-system
  name: default
spec:
  credentials:
    secretRef:
      key: credentials
      name: provider-secret
      namespace: crossplane-system
    source: Secret
